# Generated by Django 4.2.3 on 2023-08-01 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0003_review_time_edited_ticket_time_edited'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='type',
            field=models.CharField(choices=[('livre', 'Livre'), ('article', 'Article')], default='', max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ticket',
            name='title',
            field=models.CharField(max_length=128, verbose_name='Titre du <django.db.models.fields.CharField>'),
        ),
    ]
