# Generated by Django 4.2.3 on 2023-08-01 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0004_ticket_type_alter_ticket_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='type',
        ),
        migrations.AlterField(
            model_name='ticket',
            name='title',
            field=models.CharField(max_length=128, verbose_name='Titre du produit'),
        ),
    ]
