# Generated by Django 4.2.3 on 2023-08-04 00:41

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('review', '0004_remove_review_second_review_review_self_review_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SelfReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)], verbose_name='Note')),
                ('star', models.CharField(default=None, max_length=5, null=True)),
                ('headline', models.CharField(max_length=128, null=True, verbose_name='Intitulé')),
                ('body', models.TextField(blank=True, max_length=8192, null=True, verbose_name='Commentaire')),
                ('time_created', models.DateTimeField(null=True)),
                ('time_edited', models.DateTimeField(null=True)),
                ('time_last_entry', models.DateTimeField(auto_now_add=True, null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='review',
            name='self_review',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='review.selfreview'),
        ),
    ]
