# Generated by Django 4.2.3 on 2023-08-04 01:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0005_selfreview_alter_review_self_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='selfreview',
            name='ticket',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='review.ticket'),
        ),
    ]
