# Generated by Django 4.2.3 on 2023-08-04 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0006_selfreview_ticket'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='star',
            field=models.CharField(max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='selfreview',
            name='star',
            field=models.CharField(max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='time_created',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='time_edited',
            field=models.DateTimeField(null=True),
        ),
    ]
