# Generated by Django 4.2.3 on 2023-08-08 00:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0007_alter_review_star_alter_selfreview_star_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='self_review_instance',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='review',
            name='self_review',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='review.review'),
        ),
        migrations.DeleteModel(
            name='SelfReview',
        ),
    ]
