# Generated by Django 4.2.3 on 2023-08-01 03:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0008_alter_review_body_alter_review_headline_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='ticket',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='review.ticket'),
            preserve_default=False,
        ),
    ]
