# Generated by Django 4.2.3 on 2023-08-01 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0009_alter_review_ticket'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='star',
            field=models.CharField(default=None, max_length=5, null=True),
        ),
    ]
