# Generated by Django 4.2.3 on 2023-08-09 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0010_remove_ticket_time_last_entry_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='time_last_entry',
            field=models.DateTimeField(null=True),
        ),
    ]
