# Generated by Django 4.2.3 on 2023-08-15 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0015_follower_delete_userfollows'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='self_review_instance',
            new_name='is_self_review',
        ),
    ]
