# Generated by Django 4.2.3 on 2023-08-15 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0016_rename_self_review_instance_review_is_self_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='slug',
            field=models.SlugField(max_length=128, null=True),
        ),
    ]
