# Generated by Django 4.2.3 on 2023-08-16 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0018_alter_review_time_edited_alter_ticket_time_edited'),
    ]

    operations = [
        migrations.AddField(
            model_name='follower',
            name='type',
            field=models.CharField(choices=[('blocks', 'blocks'), ('follows', 'follows')], max_length=128, null=True),
        ),
    ]
