# Generated by Django 4.2.3 on 2023-08-16 11:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('review', '0019_follower_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Relation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('blocks', 'blocks'), ('follows', 'follows')], max_length=128, null=True)),
                ('description', models.CharField(max_length=255, null=True)),
                ('user_1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='follower', to=settings.AUTH_USER_MODEL)),
                ('user_2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followed', to=settings.AUTH_USER_MODEL, verbose_name="Nom d'utilisateur")),
            ],
            options={
                'unique_together': {('user_1', 'user_2')},
            },
        ),
        migrations.DeleteModel(
            name='Follower',
        ),
    ]
