# Generated by Django 4.2.3 on 2023-08-16 14:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0020_relation_delete_follower'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='overall_rating',
            field=models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)], verbose_name='Note Total'),
        ),
    ]
