# Generated by Django 4.2.3 on 2023-08-16 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0021_review_overall_rating'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticket',
            old_name='slug',
            new_name='slug_author',
        ),
        migrations.AddField(
            model_name='ticket',
            name='author',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Auteur'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='product_type',
            field=models.CharField(blank=True, choices=[('book', 'Livre'), ('article', 'Article')], max_length=128, null=True, verbose_name='Type'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='release_date',
            field=models.IntegerField(blank=True, null=True, verbose_name='Année'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='slug_title',
            field=models.SlugField(max_length=128, null=True),
        ),
    ]
