# Generated by Django 4.2.3 on 2023-08-22 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0022_rename_slug_ticket_slug_author_ticket_author_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='product_type',
            field=models.CharField(blank=True, choices=[('Livre', 'Livre'), ('Article', 'Article')], max_length=128, null=True, verbose_name='Type'),
        ),
    ]
