# Generated by Django 4.2.3 on 2023-07-27 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profil_photo',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='', verbose_name='Photo de profil'),
        ),
    ]
