# Generated by Django 4.2.3 on 2023-07-30 23:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_alter_user_profil_photo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='profil_photo',
            new_name='photo',
        ),
    ]
